"""Alembic migration environment for Relay (async, asyncpg).

The database URL is taken from ``relay.config.settings.database_url`` (never hardcoded).
``target_metadata`` is :data:`relay.db.base.Base.metadata` with all ORM models imported so
``--autogenerate`` sees them. The pgvector type is registered for autogenerate rendering.
"""

from __future__ import annotations

import asyncio
from logging.config import fileConfig

from sqlalchemy import pool
from sqlalchemy.engine import Connection
from sqlalchemy.ext.asyncio import async_engine_from_config

from alembic import context

from relay.config import settings
from relay.db.base import Base

# Import models so their tables register on Base.metadata.
import relay.db.models  # noqa: F401  (side-effect import)

config = context.config

# Inject the runtime DB URL (escape % for ConfigParser interpolation).
config.set_main_option("sqlalchemy.url", settings.database_url.replace("%", "%%"))

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = Base.metadata


def _render_item(type_, obj, autogen_context):
    """Ensure pgvector's Vector type renders with its import in autogenerated migrations."""
    from pgvector.sqlalchemy import Vector

    if type_ == "type" and isinstance(obj, Vector):
        autogen_context.imports.add("from pgvector.sqlalchemy import Vector")
        return f"Vector({obj.dim})"
    return False


def run_migrations_offline() -> None:
    """Run migrations without a DB connection (emit SQL)."""
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        compare_type=True,
        render_item=_render_item,
    )
    with context.begin_transaction():
        context.run_migrations()


def _do_run_migrations(connection: Connection) -> None:
    context.configure(
        connection=connection,
        target_metadata=target_metadata,
        compare_type=True,
        render_item=_render_item,
    )
    with context.begin_transaction():
        context.run_migrations()


async def run_migrations_online() -> None:
    """Run migrations with an async engine (asyncpg)."""
    from relay.db.base import _engine_connect_args

    connectable = async_engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
        connect_args=_engine_connect_args(settings.database_url),
    )
    async with connectable.connect() as connection:
        await connection.run_sync(_do_run_migrations)
    await connectable.dispose()


if context.is_offline_mode():
    run_migrations_offline()
else:
    asyncio.run(run_migrations_online())
